target 'Dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'

  target 'DevTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
