excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Utils/Reachability.swift

disabled_rules: # rule identifiers to exclude from running
  - nesting
  - todo

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 260
function_body_length: 60
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
identifier_name:
  allowed_symbols: ["_"] # these are allowed in type names
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
