# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Instana' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instana
  pod 'KSCrash', '~> 1.15.18'
end
