# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Instana' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instana
  # point to custom fork
  pod 'KSCrash/Core', :path => '../../KSCrash/'
  pod 'KSCrash/Reporting/Filters/AppleFmt', :path => '../../KSCrash/'
  pod 'KSCrash/Reporting/Filters/JSON', :path => '../../KSCrash/'
  pod 'KSCrash/Reporting/Filters/Tools', :path => '../../KSCrash/'
  
  target 'InstanaTests' do
      inherit! :search_paths
  end
end
